using System;
using System.Collections.Generic;
using System.Text;

namespace Api.Data.Enums
{
    public enum BetOption
    {
        HOME,
        AWAY,
        DRAW,
        HOME_HOME,
        HOME_AWAY,
        HOME_DRAW,
        DRAW_DRAW,
        AWAY_DRAW,
        AWAY_AWAY,
        HOME_YES,
        AWAY_YES,
        YES,
        NO,

        UNDER_0_25,
        OVER_0_25,
        UNDER_0_5,
        OVER_0_5,
        UNDER_0_75,
        OVER_0_75,
        UNDER_1,
        OVER_1,
        UNDER_1_25,
        OVER_1_25,
        UNDER_1_5,
        OVER_1_5,
        UNDER_1_75,
        OVER_1_75,
        UNDER_2,
        OVER_2,
        UNDER_2_25,
        OVER_2_25,
        UNDER_2_5,
        OVER_2_5,
        UNDER_2_75,
        OVER_2_75,
        UNDER_3,
        OVER_3,
        UNDER_3_25,
        OVER_3_25,
        UNDER_3_5,
        OVER_3_5,
        UNDER_3_75,
        OVER_3_75,
        UNDER_4,
        OVER_4,
        UNDER_4_25,
        OVER_4_25,
        UNDER_4_5,
        OVER_4_5,
        UNDER_4_75,
        OVER_4_75,
        UNDER_5,
        OVER_5,
        UNDER_5_25,
        OVER_5_25,
        UNDER_5_5,
        OVER_5_5,
        UNDER_5_75,
        OVER_5_75,
        UNDER_6,
        OVER_6,


        SCORE_0_0,

        SCORE_1_0,
        SCORE_2_0,
        SCORE_3_0,
        SCORE_4_0,
        SCORE_5_0,

        SCORE_0_1,
        SCORE_0_2,
        SCORE_0_3,
        SCORE_0_4,
        SCORE_0_5,

        SCORE_1_1,

        SCORE_1_2,
        SCORE_1_3,
        SCORE_1_4,
        SCORE_1_5,

        SCORE_2_1,
        SCORE_3_1,
        SCORE_4_1,
        SCORE_5_1,

        SCORE_2_2,

        SCORE_2_3,
        SCORE_2_4,
        SCORE_2_5,

        SCORE_3_2,
        SCORE_4_2,
        SCORE_5_2,

        SCORE_3_3, 

        SCORE_3_4,
        SCORE_3_5,

        SCORE_4_3,
        SCORE_5_3,

        SCORE_4_4,

        SCORE_4_5,

        SCORE_5_4,

        SCORE_5_5,


        GOALS_0,
        GOALS_1,
        GOALS_2,
        GOALS_3,
        GOALS_4,
        GOALS_5,
        GOALS_OVER_6,


        HOME_PLUS_0,
        HOME_MINUS_0,
        HOME_PLUS_0_25,
        HOME_MINUS_0_25,
        HOME_PLUS_0_5,
        HOME_MINUS_0_5,
        HOME_PLUS_0_75,
        HOME_MINUS_0_75,
        HOME_PLUS_1,
        HOME_MINUS_1,
        HOME_PLUS_1_25,
        HOME_MINUS_1_25,
        HOME_PLUS_1_5,
        HOME_MINUS_1_5,
        HOME_PLUS_1_75,
        HOME_MINUS_1_75,
        HOME_PLUS_2,
        HOME_MINUS_2,
        HOME_PLUS_2_25,
        HOME_MINUS_2_25,
        HOME_PLUS_2_5,
        HOME_MINUS_2_5,
        HOME_PLUS_2_75,
        HOME_MINUS_2_75,
        HOME_PLUS_3,
        HOME_MINUS_3,
        HOME_PLUS_3_25,
        HOME_MINUS_3_25,
        HOME_PLUS_3_5,
        HOME_MINUS_3_5,
        HOME_PLUS_4,
        HOME_MINUS_4,
        HOME_PLUS_5,
        HOME_MINUS_5,

        AWAY_PLUS_0,
        AWAY_MINUS_0,
        AWAY_PLUS_0_25,
        AWAY_MINUS_0_25,
        AWAY_PLUS_0_5,
        AWAY_MINUS_0_5,
        AWAY_PLUS_0_75,
        AWAY_MINUS_0_75,
        AWAY_PLUS_1,
        AWAY_MINUS_1,
        AWAY_PLUS_1_25,
        AWAY_MINUS_1_25,
        AWAY_PLUS_1_5,
        AWAY_MINUS_1_5,
        AWAY_PLUS_1_75,
        AWAY_MINUS_1_75,
        AWAY_PLUS_2,
        AWAY_MINUS_2,
        AWAY_PLUS_2_25,
        AWAY_MINUS_2_25,
        AWAY_PLUS_2_5,
        AWAY_MINUS_2_5,
        AWAY_PLUS_2_75,
        AWAY_MINUS_2_75,
        AWAY_PLUS_3,
        AWAY_MINUS_3,
        AWAY_PLUS_3_25,
        AWAY_MINUS_3_25,
        AWAY_PLUS_3_5,
        AWAY_MINUS_3_5,
        AWAY_PLUS_4,
        AWAY_MINUS_4,
        AWAY_PLUS_5,
        AWAY_MINUS_5,

        DRAW_PLUS_0,
        DRAW_MINUS_0,
        DRAW_PLUS_0_25,
        DRAW_MINUS_0_25,
        DRAW_PLUS_0_5,
        DRAW_MINUS_0_5,
        DRAW_PLUS_0_75,
        DRAW_MINUS_0_75,
        DRAW_PLUS_1,
        DRAW_MINUS_1,
        DRAW_PLUS_1_25,
        DRAW_MINUS_1_25,
        DRAW_PLUS_1_5,
        DRAW_MINUS_1_5,
        DRAW_PLUS_1_75,
        DRAW_MINUS_1_75,
        DRAW_PLUS_2,
        DRAW_MINUS_2,
        DRAW_PLUS_2_25,
        DRAW_MINUS_2_25,
        DRAW_PLUS_2_5,
        DRAW_MINUS_2_5,
        DRAW_PLUS_2_75,
        DRAW_MINUS_2_75,
        DRAW_PLUS_3,
        DRAW_MINUS_3,
        DRAW_PLUS_3_25,
        DRAW_MINUS_3_25,
        DRAW_PLUS_3_5,
        DRAW_MINUS_3_5,
        DRAW_PLUS_4,
        DRAW_MINUS_4,
        DRAW_PLUS_5,
        DRAW_MINUS_5,

        ODD,
        EVEN,

    }
}
